Fixes #13, Update Server Configuration
ai-cfia/louis-db pull request #14
Opened 2023-09-08 19:27 UTC by JolanThomassin

Fixes #13,
- adding "echo" to specify if the server already exist in postgres.sh.
- commenting code in lib.sh
- slight modification on the createdb line in setup-db-docker.sh

2023-09-11 14:59 UTC, rngadam requested changes

2023-09-11 14:59 UTC, rngadam commented on bin/lib.sh
> +# done
turn this into a function callable by other scripts that want to check prereqs variables outside of setup.

2023-09-11 14:59 UTC, rngadam commented on bin/postgres.sh
> +    echo container exist but as exited, restarting
echo "container exist $DB_SERVER_CONTAINER_NAME but has exited, restarting"

2023-09-11 14:59 UTC, rngadam commented on bin/postgres.sh
> +    echo container does not exist, creating
update here today

2023-09-11 14:59 UTC, rngadam commented on bin/setup-db-docker.sh
> +$DOCKER_EXEC createdb -E utf-8 -U postgres $PGBASE
Use PGUSER? can we swap for PGUSER?

2023-09-11 14:59 UTC, rngadam commented on bin/setup-db-docker.sh
>  $DOCKER_EXEC $PSQL_ADMIN -c "CREATE USER $USER; ALTER USER $USER WITH SUPERUSER;"
$USER = ton user (thomassinj)

2023-09-12 18:39 UTC, JolanThomassin commented
I've introduced a **verification function** in the last commit ([74d69c4](https://github.com/ai-cfia/louis-db/pull/14/commits/74d69c4b8d5bd3826842edd2c787c127e4e4ea64)) called `is_parameter_empty` in `lib.sh` to **validate parameters before their usage**. Currently, this function is implemented specifically for `PGPASSWORD` and `DB_SERVER_CONTAINER_NAME`.

2023-09-12 19:41 UTC, JolanThomassin commented
I've applied modification on the **verification function** in the last commit ([0ce5846](https://github.com/ai-cfia/louis-db/pull/14/commits/0ce58462b6e69a8eb78f5d735c27c909b02fb48f)), now you can utilize the function to **validate all environment variables before their usage**, if any of them are undefined or empty, **the execution will stop**.

2023-09-12 19:43 UTC, rngadam requested changes

2023-09-12 19:46 UTC, rngadam requested changes
also add usage information to the README.md in bin/

2023-09-12 19:46 UTC, rngadam commented on bin/lib.sh
>      fi
tabulation? please add a bash shell script linter

2023-09-12 19:46 UTC, rngadam commented on bin/postgres.sh
> +    echo container does not exist, creating
more details in your string, including container name

2023-09-12 19:46 UTC, rngadam commented on bin/postgres.sh
>      docker run --name louis-db-server \
this should be using your environment variable...

2023-09-12 19:46 UTC, rngadam commented on bin/setup-db-docker.sh
>  DOCKER_EXEC="docker exec -it louis-db-server"
idem

2023-09-13 13:21 UTC, rngadam approved these changes

2023-09-13 13:21 UTC, rngadam commented on bin/lib.sh
> +        exit 1
be nice and tell the user why you are exiting

2023-09-13 15:36 UTC, JolanThomassin commented
In this commit, I have replace existing **variable names with environment variables**. This update **enhances the flexibility** by allowing configuration settings to be **managed externally** through environment variables, making it easier to **adapt to different deployment environments**.

2023-09-13 15:38 UTC, rngadam approved these changes

2023-09-13 15:48 UTC, JolanThomassin commented
We observed that the code exhibited a **high degree of specificity towards `louis-db`.** To enhance flexibility, we have initiated a new issue : https://github.com/ai-cfia/louis-db/issues/15

2023-09-13 17:15 UTC, merged