Merge pull request #30 from ai-cfia/28-louis-db-readme-improvment
ai-cfia/louis-db pull request #35
Opened 2023-10-24 23:20 UTC by leejaeka

Adding 'vis' folder to contain vis.ipynb notebook that outputs 2d visualisation of vector space

2023-10-25 20:21 UTC, rngadam requested changes
you should create a corresponding issue and create a branch based on that issue name. see Editing-code-in-WSL-with-Visual-Studio-Code in the internal wiki

2023-10-25 20:21 UTC, rngadam commented on vis/notebook/vis.ipynb
> +        "!nomic login 'HfFeBu516-CFtRnOFlEY9k-A5DWMqyKrhNe7XyxSv3irV'\n",
note that you've embedded the nomic login token into the notebook source; it's bad practice to store secrets in the source.

there's a way to use secrets from codespaces: https://docs.github.com/en/codespaces/managing-your-codespaces/managing-secrets-for-your-codespaces

these show up as environment variables.

2023-10-26 05:55 UTC, leejaeka reviewed
replaced nomic api key with github codespace secrets

2023-10-30 20:33 UTC, rngadam requested changes

2023-10-30 20:33 UTC, rngadam commented on vis/notebook/vis.ipynb
> -        "!nomic login 'HfFeBu516-CFtRnOFlEY9k-A5DWMqyKrhNe7XyxSv3irV'\n",
the key is still in the history.

1) rebase to squash your changes into a single commit.
2) make sure you've invalidated this key so it doesn't work anymore (as you have to assume someone scraped it)

2023-11-02 03:37 UTC, closed without merging